### ISSUE TITLE
overview mode

### ISSUE THREAD

**Issue by timofei7** [tasmo/reveal-jekyll#4]
doesn't seem to be working. the future and past slides are all offscreen.  trying to figure it out, but any insight appreciated!

**Comment by timofei7** [comment]
ah!  in `_config.yml` the width and height were causing the transform applied in overview mode to be crazy: `translate3d(480280px, 0px, 0px);`. 

turns out that these are being inserted as single quoted strings when processed in `script.html`. vanilla reveal will run into this problem also if width and height are specific as strings.  I think the easy fix is to just check if the attributes are width/height. seems most other things are happy being quoted.

**Comment by tasmo** [comment]
Thank you for finding out!
