### ISSUE TITLE
Broken build: gitsubmodule error

### ISSUE THREAD

**Issue by sbstn-jmnz** [tasmo/reveal-jekyll#8]
Hi! Awesome repo, but it has a problem with its submodule config.
This is the aoutupt, both in local and in build time:

fatal: remote error: upload-pack: not our ref 45be1d916851880d2de13e547d10539c10d5a8c5
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'reveal.js', but it did not contain 45be1d916851880d2de13e547d10539c10d5a8c5. Direct fetching of that commit failed.

There is no reference to that hash in reveal's repo.

In trying to fix this.

**Comment by tasmo** [comment]
Thank you @sbstn-jmnz for reporting!
